### ISSUE TITLE
Initial documentation gets deleted when doing a partial build

### ISSUE THREAD

**Issue by wfulp** [RGLab/DataPackageR#12]
roxygenise function seems to delete all the initial documentation when doing a partial build. Here is the relevant area to address I believe (from `buildDataSetPackage` function):

```
  message("Removing old documentation.")
  manfiles = list.files(path=packageName,pattern = "\\.Rd$",ignore.case = FALSE,full.names=TRUE,recursive=TRUE)
  sapply(manfiles,file.remove)
  message("Building documentation")
  roxygenise(packageName)
```
I tried wrapping the first three line to only run during full build, but roxygenise seems to delete the documentation anyways.

**Comment by wfulp** [comment]
I'm still getting the help filed deleted when running a partial build. `clean = FALSE` is the default in `roxygenise` function, so I'm not sure if I expect the line ` roxygenise(packageName,clean=ifelse(is.null(masterfile),TRUE,FALSE))` to fix the problem.

**Comment by gfinak** [comment]
Roxygenise will delete the existing documentation, that's its behavior and it's not modifiable without getting into the internals. 
Probably need to change how the documentation is assembled before this call

**Comment by wfulp** [comment]
Could you just move (or copy) the *.Rd files before running the roxygenise function, and then move them back after the partial build *.Rd files are created? Maybe you'll need to only move back files not created in the partial build.

**Comment by gfinak** [comment]
Or append the roxygen code to the existing .R file
