### ISSUE TITLE
Mentioning similar work: datastorr, fst, etc.

### ISSUE THREAD

**Issue by wlandau** [RGLab/DataPackageR#21]
Hi @gfinak,

I am reviewing `DataPackageR` for https://github.com/ropensci/onboarding/issues/230, and I have decided to create separate issues for my comments so we can discuss more easily. Once I have posted all my comments, I will submit my formal review to https://github.com/ropensci/onboarding/issues/230, which will cross reference them. I recommend [creating a custom label](https://github.com/RGLab/DataPackageR/labels) to keep track of these issues.

Anyway, as mentioned in [this thread from the 2018 Unconference](https://github.com/ropensci/unconf18/issues/28), @noamross has a [slide deck](https://github.com/noamross/2018-04-18-rstats-nyc/blob/master/Noam_Ross_ModernDataPkg_rstatsnyc_2018-04-20.pdf) in which he describes existing work on data packaging, such as [`datastorr`](https://github.com/ropenscilabs/datastorr) and [`fst`](http://www.fstpackage.org/). Would you consider adding a section to the `README` that points to this existing work and emphasizes the strengths of `DataPackageR` in this landscape?

**Comment by gfinak** [comment]
@wlandau, happy to do it. Thanks for pointing these out as well, I was not aware of them. I think they can be quite complementary with DataPackageR.

**Comment by gfinak** [comment]
@wlandau thanks for the review and the suggestions, I look forward to addressing  and implementing these changes, I think they'll make the package significantly better.

**Comment by wlandau** [comment]
Glad this is helpful. Your new ["Similar work"](https://github.com/RGLab/DataPackageR#similar-work) section is great.
