### ISSUE TITLE
Refactoring the vignette

### ISSUE THREAD

**Issue by wlandau** [RGLab/DataPackageR#25]
Here, I do not think you need to repeat the motivation and installation sections from the README. After maybe a brief intro, you can jump right into usage. You may want to consider expanding the code chunk from #24. I recommend the following areas of focus:

- Building and installing ~~the package~~ data packages.
- Making it clear that the processed data enters the built package and the raw data is left out, but the source still has a reproducible record of the data processing.
- Demonstrate loading the package and accessing the data.
- The fields of the YAML file.
- Data versioning
- `DATADIGEST`
- Partial builds and data migration as separate sections.

**Comment by wlandau** [comment]
To be clear, the above list of sections is just a loose suggestion. I am only trying to give you some ideas, not trying to force you into a specific structure. This thread may also be helpful: https://github.com/ropensci/onboarding-meta/issues/55.

**Comment by gfinak** [comment]
I believe the latest changes address the remaining comments on #24 and #25

**Comment by wlandau** [comment]
Looks good, thanks.
