### ISSUE TITLE
Consider a dedicated guide on just the YAML configuration file

### ISSUE THREAD

**Issue by wlandau** [RGLab/DataPackageR#32]
You touched on the YAML configuration file in the vignette, and it looks useful. I think new users would appreciate a dedicated vignette on that file describing

- Its purpose in governing how data is processed.
- What all the fields mean.
- Which `yml_*()` functions are available and what they do.
- An example project that relies on manually modifying the YAML file.

**Comment by wlandau** [comment]
Just saw the [remarks in the vignette](https://github.com/RGLab/DataPackageR/blob/master/vignettes/usingDataPackageR.Rmd) and [`YAML_CONFIG.md`](https://github.com/RGLab/DataPackageR/blob/master/YAML_CONFIG.md). I consider this issue solved, but I have 2 questions:

1. Is there a reason you need the name of each script file to be repeated in the `name` field? I believe full paths with slashes can still be valid YAML keys.
2. Is there a reason you prefer [`YAML_CONFIG.md`](https://github.com/RGLab/DataPackageR/blob/master/YAML_CONFIG.md) to be a top-level Markdown document rather than a vignette?

**Comment by gfinak** [comment]
1. I wasn't aware that full paths could be keys. I think I could make that change with minimal impact. Will work on it.
2. No particular reason. I can make it a package vignette instead.

**Comment by wlandau** [comment]
I might actually be wrong about (1) because I did not test with paths with spaces. Sorry about that. Is there still a way to avoid having to duplicate information in the YAML?

**Comment by gfinak** [comment]
Well, paths aren't part of the yaml actually. scripts are stored under data-raw and that path in handled by `usethis::proj_get` and `usethis::proj_set`
